import type { Metadata } from 'next';
import { db } from '../db';
import { Geist, Geist_Mono } from 'next/font/google';
import Sidebar from '@/src/components/Sidebar';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tree = await db.query.pages.findMany({
    where: { parentId: { isNull: true }, deletedAt: { isNull: true } },
    orderBy: { position: 'asc' },
    with: {
      children: {
        where: { deletedAt: { isNull: true } },
        orderBy: { position: 'asc' },
      },
    },
  });
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="h-full flex">
        <Sidebar pages={tree} />
        <main className="flex-1 min-w-0 overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}
